version: '3.4'

services:
    php:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8402:5000"
        depends_on:
            - mysql
        volumes:
            - .:/srv/app

    fpm:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: php-fpm
        depends_on:
            - mysql
        volumes:
            - .:/srv/app

    openswoole:
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        entrypoint: [php, public/openswoole.php]
        depends_on:
            - mysql
        volumes:
            - .:/srv/app

    cmd:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - mysql
        command: /bin/sh
        entrypoint: ""
        volumes:
            - .:/srv/app

    mysql:
        image: mariadb:10.4
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: blog
            MYSQL_USER: blog
            MYSQL_PASSWORD: f]tKaV6b-N7!UNQP
        volumes:
            - ./var/mysql:/var/lib/mysql
            - ./blog.sql:/docker-entrypoint-initdb.d/blog.sql
        command: --default-authentication-plugin=mysql_native_password --wait_timeout=28800

    nginx:
        image: nginx:latest
        ports:
            - "8401:80"
        depends_on:
            - php
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - .:/srv/app
